### PR TITLE
Add command to visualise backlinks

### PR DESCRIPTION
**Pull request by skissue**
Adds the command `denote-explore-backlinks-barchart`, which shows the top N nodes sorted by backlink count along with their number of backlinks.

I'm not sure about the implementation of `backlinks` as a property of nodes in the graph. I created a separate `denote-explore--network-backlinks` to calculate them, but it could also be folded into `denote-explore--network-degree` by calculating the in-degree and out-degree separately.

### CODE REVIEW

**Comment by pprevos** [comment]
Hi Ad,

Thanks for the enhancements. Perhaps this idea can be generalised with a function for in-degree and out-degree distributions, plus the existing total degree. We can then calculate centrality metrics such as pagerank.

Why are you also modiying `denote-explore-network-community-graph`? Are you suggestion to size nodes by backlink instead of total degree?

Perhaps that should be a user option.

**Comment by skissue** [comment]
> Why are you also modiying `denote-explore-network-community-graph`? Are you suggestion to size nodes by backlink instead of total degree?

I saw that `denote-explore-degree-barchart` works by calling `denote-explore-network-community-graph`, and parsing the resulting `degree` property on each node (via `denote-explore--network-sum-degrees`). I modified `denote-explore-network-community-graph` to also include a `backlinks` property on every node, which is what `denote-explore-backlinks-barchart` uses. Admittedly, this is not the cleanest solution; it may be better to simply change `denote-explore--network-degree` to add an `in-degree` and `out-degree` property to each node instead.

> Perhaps this idea can be generalised with a function for in-degree and out-degree distributions, plus the existing total degree. We can then calculate centrality metrics such as pagerank.

Yes, that's a possibility I was thinking (and would be implementing the above sentence). I can change the PR to refactor `denote-explore--network-degree` instead.

**Comment by pprevos** [comment]
You are correct, I should not have reused that function. I will have time this weekend to look at it further. Contributions are of course welcome :)

**Comment by pprevos** [comment]
I merged this commit into a test branch to develop it further.

**Comment by pprevos** [comment]
Hi Ad, I have merged your function in to the main branch and it to the manual. I have also flipped the chart horizontally to make it easier to read. Thanks for the contribution.

**Pull request merged**
